config/routes.rb
Firefight::Application.routes.draw do
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' }

  resources :members do
    collection do
      get :get_troops_stats
      get :get_trophies_stats
    end
  end
  
  resources :stat_groups
  resources :stat_periods
  
  resources :stats do
    collection do
      get :top_rankings
    end
  end

  get "home/index"
  get "home/about", as: "about"
  
  match "sleep" => "home#sleep"

  root :to => "home#sleep", :constraints => { :subdomain => "hasmarvsgonetobedyet" }
  root :to => 'home#index'

end

app/models/stat_group.rb
class StatGroup < ActiveRecord::Base
  attr_accessible :creator_id, :stat_period_id
  
  # Relations
  belongs_to :creator, :class_name => "User"
  belongs_to :stat_period
  has_many :stats
  
  scope :recent_first, order("created_at DESC")
  
end

app/controllers/stat_groups_controller.rb
class StatGroupsController < ApplicationController
  before_filter :require_admin, :except => [:index, :show]
  before_filter :set_navbar_active

  def index
    @stat_groups = StatGroup.order('created_at DESC').all
  end
  
  def show
    @stat_group = StatGroup.find(params[:id])
  end
  
  def new
    @stat_group = StatGroup.new
    @stats = []
    last_stat = StatGroup.last
    if last_stat.nil? || !last_stat.stats.any?
      # Try to create a new form
      # Get top 50 members, sorted by trophy count
      members = Member.clan_members.all
      members.each do |mem|
        @stats << Stat.new({:member_id => mem.id})
      end
    else
      # Create the form based on the last data
      prev_stats = last_stat.stats.order("trophies DESC").all
      prev_stats.each do |ps|
        if ps.member && ps.member.active
          attrs = { level: ps.level, donated: ps.donated, received: ps.received, 
                    trophies: ps.trophies, member_id: ps.member_id }
          @stats << Stat.new(attrs)
        end
      end
    end
    if @stats.size < 50
      @new_members = Member.clan_members.all - @stat_group.stats.map(&:member) rescue []
      (50 - @stats.size).times do
        @stats << Stat.new
      end
    end
  end
  
  def create
    members = params[:member_id]
    levels = params[:level]
    donated = params[:donated]
    received = params[:received]
    trophies = params[:trophies]
    @stat_group = StatGroup.create!(:creator_id => 1, :stat_period_id => params[:stat_group][:stat_period_id])
    
    members.each_with_index do |mid, index|
      mem = Member.clan_members.where(id: mid).first
      if mem && mem.active
        stat = Stat.new(stat_group_id: @stat_group.id, member_id: mid)
        stat.level = levels[index]
        stat.donated = donated[index]
        stat.received = received[index]
        stat.trophies = trophies[index]
        stat.save!
      end
    end
    redirect_to :action => :index
  end
  
  def edit
    @stat_group = StatGroup.find(params[:id])
    if @stat_group
      @members = []
      @stats = @stat_group.stats.order("trophies DESC, id ASC").all
      @stats.each do |stat|
        @members << [stat.member.name, stat.member.id] if stat.member
      end
      if @stats.size < 50
        @new_members = Member.clan_members.all - @stat_group.stats.map(&:member) rescue []
        (50 - @stats.size).times do
          @stats << Stat.new(stat_group_id: @stat_group.id)
        end
      end
    else
      redirect_to :action => :index
    end
  end
  
  def update
    @stat_group = StatGroup.find(params[:id])
    if @stat_group
      @stat_group.update_attribute(:stat_period_id, params[:stat_group][:stat_period_id])
      members = params[:member_id]
      levels = params[:level]
      donated = params[:donated]
      received = params[:received]
      trophies = params[:trophies]
      members.each_with_index do |mid, index|
        mem = Member.clan_members.where(id: mid).first
        if mem && mem.active
          stat = Stat.find_or_create_by_stat_group_id_and_member_id(@stat_group.id, mid)
          stat.level = levels[index]
          stat.donated = donated[index]
          stat.received = received[index]
          stat.trophies = trophies[index]
          stat.save!
        end
      end
    end  
    redirect_to :action => :index
  end
  
  def destroy
    @stat_group = StatGroup.find(params[:id])
    created_on = @stat_group.created_at
    @stat_group.destroy
    redirect_to stat_groups_path, :notice => "Deleted StatGroup created on #{created_on.to_s}!"
  end
  
  
private
  def set_navbar_active
    @navbar_active = "stats"
  end  
  
end

app/views/stat_groups/_form.html.haml
= form_for @stat_group do |f|
  .control-group
    = f.collection_select :stat_period_id, StatPeriod.recent_first.all, :id, :name, {}, :class => "span3"
  %table.table.table-hover.stat_group
    %thead
      %tr
        %th No.
        %th Level
        %th Member
        %th Troops Donated
        %th Troops Received
        %th Trophies
    %tbody
      - @stats.each_with_index do |stat, index|
        - selmem = stat.member
        %tr
          %td= index + 1
          %td= text_field_tag "level[]", stat.level
          %td
            - if selmem
              = hidden_field_tag "member_id[]", selmem.id
              = selmem.name
            - else
              = select_tag "member_id[]", options_from_collection_for_select(@new_members, 'id', 'name'), :include_blank => true
          %td= text_field_tag "donated[]", stat.donated
          %td= text_field_tag "received[]", stat.received
          %td= text_field_tag "trophies[]", stat.trophies
  
  = submit_tag "Save Stats", class: 'btn btn-primary'

app/views/stat_groups/edit.html.haml
%h1 Modify Stat Group
%h2= @stat_group.created_at.to_s

= render 'form'

app/views/stat_groups/index.html.haml
- StatPeriod.recent_first.each do |sp|
  %h3= sp.name
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Date
        %th Members
        %th Trophies  
        %th Troops Donated
        %th Troops Received
        - if admin_user?
          %th Actions
    %tbody
      - sp.stat_groups.recent_first.each do |sg|
        %tr
          %td= link_to sg.created_at.to_s(:normal_datetime), sg
          %td= sg.stats.count
          %td= sg.stats.sum(:trophies)
          %td= sg.stats.sum(:donated)
          %td= sg.stats.sum(:received)
          - if admin_user?
            %td
              = link_to "Edit", edit_stat_group_path(sg)
              |
              = link_to "Delete", stat_group_path(sg), method: :delete, confirm: "Are you sure you want to delete this stat group?"

- if StatGroup.recent_first.where(:stat_period_id => nil).any?            
  %h4 Uncategorized Stats
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Date
        %th Members
        %th Trophies  
        %th Troops Donated
        %th Troops Received
        - if admin_user?
          %th Actions
    %tbody
      - StatGroup.recent_first.where(:stat_period_id => nil).each do |sg|
        %tr
          %td= link_to sg.created_at.to_s(:normal_datetime), sg
          %td= sg.stats.count
          %td= sg.stats.sum(:trophies)
          %td= sg.stats.sum(:donated)
          %td= sg.stats.sum(:received)
          - if admin_user?
            %td
              = link_to "Edit", edit_stat_group_path(sg)
              |
              = link_to "Delete", stat_group_path(sg), method: :delete, confirm: "Are you sure you want to delete this stat group?"

app/views/stat_groups/new.html.haml
%h1 Create New Stat Group

= render 'form'

app/views/stat_groups/show.html.haml
%h3 Stats from #{@stat_group.created_at.to_s(:normal_datetime)}

%table.table.table-hover.stat_group
  %thead
    %tr
      %th No.
      %th Level
      %th Member
      %th Troops Donated
      %th Troops Received
      %th Trophies
  %tbody
    - @stat_group.stats.trophies_desc.each_with_index do |stat, index|
      %tr
        %td= index + 1
        %td= stat.level
        %td
          %strong= link_to stat.member.name, stat.member rescue '(missing record)'
        %td= stat.donated
        %td= stat.received
        %td= stat.trophies