config/routes.rb
Firefight::Application.routes.draw do
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' }

  resources :members do
    collection do
      get :get_troops_stats
      get :get_trophies_stats
    end
  end
  
  resources :stat_groups
  resources :stat_periods
  
  resources :stats do
    collection do
      get :top_rankings
    end
  end

  get "home/index"
  get "home/about", as: "about"
  
  match "sleep" => "home#sleep"

  root :to => "home#sleep", :constraints => { :subdomain => "hasmarvsgonetobedyet" }
  root :to => 'home#index'

end

app/models/stat_period.rb
class StatPeriod < ActiveRecord::Base
  attr_accessible :end_date, :name, :start_date
  
  # Validations
  validates_presence_of :start_date, :end_date, :name
  
  # Relations
  has_many :stat_groups
  
  # Scope
  scope :recent_first, order("created_at DESC")
  
end

app/controllers/stat_periods_controller.rb
class StatPeriodsController < ApplicationController
  before_filter :require_admin
  before_filter :set_navbar_active

  def index
    @stat_periods = StatPeriod.order('created_at DESC').all
  end
  
  def new
    @stat_period = StatPeriod.new
  end
  
  def create
    @stat_period = StatPeriod.new(params[:stat_period])
    if @stat_period.save
      flash[:notice] = "Created stat period!"
      redirect_to :action => :index
    else
      render :action => :new
    end
  end
  
  def edit
    @stat_period = StatPeriod.find(params[:id])
  end
  
  def update
    @stat_period = StatPeriod.find(params[:id])
    if @stat_period.update_attributes(params[:stat_period])
      flash[:notice] = "Updated stat period!"
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end
  
  def destroy
    @stat_period = StatPeriod.find(params[:id])
    created_on = @stat_period.created_at
    @stat_period.destroy
    redirect_to stat_periods_path, :notice => "Deleted StatPeriod created on #{created_on.to_s}!"
  end
  
  
private
  def set_navbar_active
    @navbar_active = "stats"
  end  
  
end

app/views/stat_periods/_form.html.haml
= form_for @stat_period, :html => { class: 'form-horizontal well' } do |f|
  %fieldset
    %legend Add/Update New Member
    .control-group
      %label.control-label Name
      .controls
        = f.text_field :name
    .control-group
      %label.control-label Start Date
      .controls
        = f.date_select :start_date
    .control-group
      %label.control-label End Date
      .controls
        = f.date_select :end_date
    .form-actions
      = f.submit "Save", class: 'btn btn-primary'
      = link_to "Cancel", stat_periods_path, class: 'btn'
      
:javascript
  // This will make the control-group to have the error class if the field has an error
  $('input').each(function() {
    if ($(this).parent().hasClass('error')) {
      $(this).closest('.control-group').addClass('error');
    } 
  });

app/views/stat_periods/edit.html.haml
= render 'form'

app/views/stat_periods/index.html.haml
.row
  .span-12
    %h3 Stat Periods
    %p= link_to "New Period", new_stat_period_path

%table.table.table-striped.table-hover
  %thead
    %tr
      %th Name
      %th Start Date
      %th End Date
      %th Actions
  %tbody
    - @stat_periods.each do |stat_period|
      %tr
        %td
          = stat_period.name
        %td
          = stat_period.start_date
        %td
          = stat_period.end_date  
        %td
          - if admin_user?
            %td= link_to "Edit", edit_stat_period_path(stat_period)
            

app/views/stat_periods/new.html.haml
= render 'form'