config/routes.rb
Firefight::Application.routes.draw do
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' }

  resources :members do
    collection do
      get :get_troops_stats
      get :get_trophies_stats
    end
  end
  
  resources :stat_groups
  resources :stat_periods
  
  resources :stats do
    collection do
      get :top_rankings
    end
  end

  get "home/index"
  get "home/about", as: "about"
  
  match "sleep" => "home#sleep"

  root :to => "home#sleep", :constraints => { :subdomain => "hasmarvsgonetobedyet" }
  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :max_trophies, :max_levels, :max_donations, :admin_user?
  
  def require_admin
    redirect_to root_path unless admin_user?
  end
  
  def admin_user?
    user_signed_in? && current_user.admin?
  end
  
  def max_trophies(limit=5)
    @max_trophies = []
    Member.clan_members.each do |mem|
      highest_stat = Stat.with_trophies.where(member_id: mem.id).order("trophies DESC").limit(1).first
      if highest_stat
        @max_trophies << highest_stat
      end
    end
    @max_trophies.sort_by(&:trophies).reverse.take(limit) rescue []
  end
  
  def max_levels(limit=5)
    @max_levels = []
    Member.clan_members.each do |mem|
      highest_stat = Stat.with_levels.where(member_id: mem.id).order("level DESC").limit(1).first
      if highest_stat
        @max_levels << highest_stat
      end
    end
    @max_levels.sort_by(&:level).reverse.take(limit) rescue []
  end
  
  def max_donations(limit=5)
    @max_donations = []
    Member.clan_members.each do |mem|
      highest_stat = Stat.with_donations.where(member_id: mem.id).order("donated DESC").limit(1).first
      if highest_stat
        @max_donations << highest_stat
      end
    end
    @max_donations.sort_by(&:donated).reverse.take(limit) rescue []
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.haml
%hr/
%footer
  %p 
    © Mambin 2013. Clan logo and 'Clash of Clans' © 
    = link_to "Supercell", "http://www.supercell.net/"

app/views/application/_navbar.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href => "#", style: "padding: 10px 15px;"}
        = image_tag "clan_logo_nav.png"
      %a.brand{:href => root_path}
        = Rails.application.config.site_name
      .nav-collapse.collapse#main-menu
        %ul.nav#main-menu-left
          %li{ class: (@navbar_active == "home") ? 'active' : nil }
            %a{:href => root_path} Home
          %li{ class: (@navbar_active == "about") ? 'active' : nil }
            %a{:href => about_path} About
          %li.dropdown{ class: (@navbar_active == "members") ? 'active' : nil }
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Members
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Member List", members_path
              - if admin_user?
                %li= link_to "New Member", new_member_path
          %li.dropdown{ class: (@navbar_active == "stats") ? 'active' : nil }
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Stats
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Stats List", stat_groups_path
              - if admin_user?
                %li= link_to "New Entry", new_stat_group_path
                %li= link_to "Stat Periods", stat_periods_path
              %li.divider
              %li.nav-header Records
              %li
                = link_to "Top Rankings", top_rankings_stats_path
              %li
                %a{:href => "#"} Graphs
        %ul.nav.pull-right#main-menu-right
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                = current_user.email
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Logout", destroy_user_session_path, :method => :delete
          %li
            = link_to "Join the Facebook Group!", "https://www.facebook.com/groups/firefight13/", :rel => "tooltip", :target => "_blank"
          