config/routes.rb
Firefight::Application.routes.draw do
  
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout', :registration => 'register' }

  resources :members do
    collection do
      get :get_troops_stats
      get :get_trophies_stats
    end
  end
  
  resources :stat_groups
  resources :stat_periods
  
  resources :stats do
    collection do
      get :top_rankings
    end
  end

  get "home/index"
  get "home/about", as: "about"
  
  match "sleep" => "home#sleep"

  root :to => "home#sleep", :constraints => { :subdomain => "hasmarvsgonetobedyet" }
  root :to => 'home#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :active, :name, :elder
  
  scope :elders, where(elder: true)
  scope :clan_members, where(active: true)
  scope :former, where(active: false)
  
  # Relations
  has_many :stats
  
  # Validations
  validates_presence_of :name
  validates_uniqueness_of :name
  
  def member?
    self.active == true
  end
  
  def get_stats
    self.stats.recent_first
  end
  
  def get_stats_per_period(sp)
    self.stats.recent_first.where(:stat_group_id => sp.stat_groups.map(&:id))
  end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :require_admin, :except => [:index, :show, :get_troops_stats, :get_trophies_stats]
  before_filter :set_navbar_active

  def index
    @members = Member.order(:name)
  end
  
  def new
    @member = Member.new
  end
  
  def show
    @member = Member.find(params[:id])
  end
  
  def create
    @member = Member.new(params[:member])
    if @member.save
      redirect_to :action => :index
    else
      render :new
    end
  end
  
  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])
    if @member.update_attributes(params[:member])
      redirect_to :action => :index
    else
      render :edit
    end
  end
  
  def get_troops_stats
    @member = Member.find(params[:id])
    donated = []
    received = []
    data = []
    @member.stats.each do |stat|
      donated << { x: stat.created_at.utc.to_date.to_s, y: stat.donated }
      received << { x: stat.created_at.utc.to_date.to_s, y: stat.received }
    end
    # Or use (Time.now.to_f * 1000).to_i instead of javascript getTime()ss
    data << { values: donated, key: "Troops Donated", color: '#00FF00' }
    data << { values: received, key: "Troops Received", color: '#FF0000' }
    render :json => data
  end
  
  def get_trophies_stats
    @member = Member.find(params[:id])
    trophies = []
    data = []
    @member.stats.each do |stat|
      trophies << { x: stat.created_at.utc.to_date.to_s, y: stat.trophies }
    end
    data << { values: trophies, key: "Trophies", color: '#00FF00' }
    render :json => data
  end
  
  
private
  def set_navbar_active
    @navbar_active = "members"
  end  
  
end

app/views/members/_form.html.haml
= form_for @member, :html => { class: 'form-horizontal well' } do |f|
  %fieldset
    %legend Add New Member
    .control-group
      %label.control-label{:for => "input01"} Text input
      .controls
        = f.text_field :name
        %p.help-block Please note that names are case-sensitive!
    .control-group
      %label.control-label{:for => "optionsCheckbox"} Elder?
      .controls
        %label.checkbox
          = f.check_box :elder
          Check if this member is an elder
    .control-group
      %label.control-label{:for => "optionsCheckbox"} Member?
      .controls
        %label.checkbox
          = f.check_box :active
          Check if this member is a member of the clan
    .form-actions
      = f.submit "Add Member", class: 'btn btn-primary'
      = link_to "Cancel", members_path, class: 'btn'
      
:javascript
  // This will make the control-group to have the error class if the field has an error
  $('input').each(function() {
    if ($(this).parent().hasClass('error')) {
      $(this).closest('.control-group').addClass('error');
    } 
  });

app/views/members/index.html.haml
%h3= "Current Members: #{@members.clan_members.count}"

%table.table.table-striped.table-hover
  %tbody
    - @members.clan_members.each do |member|
      %tr
        %td{ style: 'font-size: 18px;' }
          %strong= link_to member.name, member
        %td
          = "(#{member.slug})"
        %td
          - if member.active
            %span.label.label-info Clan Member
          - else
            &nbsp;
        - if admin_user?
          %td= link_to "Edit", edit_member_path(member)
          
          
%h3= "Former Members: #{@members.former.count}"    

%table.table.table-striped.table-hover
  %tbody
    - @members.former.each do |member|
      %tr
        %td{ style: 'font-size: 18px;' }
          %strong= link_to member.name, member
        %td
          = "(#{member.slug})"
        %td
          - if member.active
            %span.label.label-info Clan Member
          - else
            &nbsp;
        - if admin_user?
          %td= link_to "Edit", edit_member_path(member)

app/views/members/show.html.haml
.page-header
  %h1 
    = @member.name
    - if @member.member?
      %small Clan Member
      
.row-fluid
  %ul.thumbnails
    %li.span6
      .thumbnail
        #line_troops
          %svg{ style: 'height: 400px' }
        .caption
          %h3 Troops Received vs Troops Donated
    %li.span6
      .thumbnail
        #line_trophies
          %svg{ style: 'height: 400px' }
        .caption
          %h3 Trophies

- StatPeriod.recent_first.each do |sp|
  - if @member.get_stats_per_period(sp).any?
    %div{ :style => "text-align: center;" }
      %h3= sp.name
    %table.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %th Date
          %th Level
          %th Troops Donated
          %th Troops Received
          %th Trophies
      %tbody
        - @member.get_stats_per_period(sp).each do |stat|
          %tr
            %td= stat.created_at.to_s(:normal_datetime)
            %td= stat.level
            %td= stat.donated
            %td= stat.received
            %td= stat.trophies
        
#member_name{ style: 'display:none;' }= @member.slug        
%script{ src: "#{asset_path('charts/line_troops.js')}" }
%script{ src: "#{asset_path('charts/line_trophies.js')}" }